[package]
name = "ifcomp"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "2"
hdiff = { git = "https://github.com/sergev/hdiff" }

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
rand = "0.8"
